//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimplyNotedUiWpf.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Literals {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Literals() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimplyNotedUiWpf.Properties.Literals", typeof(Literals).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        public static string MainView_DeleteNoteButton_Content {
            get {
                return ResourceManager.GetString("MainView_DeleteNoteButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New ähnelt.
        /// </summary>
        public static string MainView_NewNoteButton_Content {
            get {
                return ResourceManager.GetString("MainView_NewNoteButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Created: ähnelt.
        /// </summary>
        public static string MainView_Note_CreatedLabel_Content {
            get {
                return ResourceManager.GetString("MainView_Note_CreatedLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Modified: ähnelt.
        /// </summary>
        public static string MainView_Note_ModifiedLabel_Content {
            get {
                return ResourceManager.GetString("MainView_Note_ModifiedLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Created (latest) ähnelt.
        /// </summary>
        public static string MainView_NoteList_ContextMenu_Sorting_CreatedLatest {
            get {
                return ResourceManager.GetString("MainView_NoteList_ContextMenu_Sorting_CreatedLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Created (oldest) ähnelt.
        /// </summary>
        public static string MainView_NoteList_ContextMenu_Sorting_CreatedOldest {
            get {
                return ResourceManager.GetString("MainView_NoteList_ContextMenu_Sorting_CreatedOldest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Modified (latest) ähnelt.
        /// </summary>
        public static string MainView_NoteList_ContextMenu_Sorting_ModifiedLatest {
            get {
                return ResourceManager.GetString("MainView_NoteList_ContextMenu_Sorting_ModifiedLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Modified (oldest) ähnelt.
        /// </summary>
        public static string MainView_NoteList_ContextMenu_Sorting_ModifiedOldest {
            get {
                return ResourceManager.GetString("MainView_NoteList_ContextMenu_Sorting_ModifiedOldest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Title (ascending) ähnelt.
        /// </summary>
        public static string MainView_NoteList_ContextMenu_Sorting_TitleAscending {
            get {
                return ResourceManager.GetString("MainView_NoteList_ContextMenu_Sorting_TitleAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Title (descending) ähnelt.
        /// </summary>
        public static string MainView_NoteList_ContextMenu_Sorting_TitleDescending {
            get {
                return ResourceManager.GetString("MainView_NoteList_ContextMenu_Sorting_TitleDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string MainView_SaveNoteButton_Content {
            get {
                return ResourceManager.GetString("MainView_SaveNoteButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Simply Noted ähnelt.
        /// </summary>
        public static string MainView_Title {
            get {
                return ResourceManager.GetString("MainView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to delete the current note with the title &quot;{0}&quot; created at {1}? ähnelt.
        /// </summary>
        public static string MainViewModel_DeleteNote_ConfirmationMessage {
            get {
                return ResourceManager.GetString("MainViewModel_DeleteNote_ConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete Note ähnelt.
        /// </summary>
        public static string MainViewModel_DeleteNote_ConfirmationTitle {
            get {
                return ResourceManager.GetString("MainViewModel_DeleteNote_ConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Note ähnelt.
        /// </summary>
        public static string MainViewModel_NewNote_DefaultTitle {
            get {
                return ResourceManager.GetString("MainViewModel_NewNote_DefaultTitle", resourceCulture);
            }
        }
    }
}
